// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UUSTAbiturientChance.DataAccess;

#nullable disable

namespace UUSTAbiturientChance.DataAccess.Migrations
{
    [DbContext(typeof(UUSTAbiturientChanceDbContext))]
    [Migration("20250720090847_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UUSTAbiturientChance.Application.Srvices.Entities.ApplicantEntity", b =>
                {
                    b.Property<string>("UniqueCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppliedPrograms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasEnrollmentConsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFirstPriorityRightArticle")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNoEntranceTests")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSecondPriorityRightArticle")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("IndividualAchievementsScore")
                        .HasColumnType("integer");

                    b.Property<int>("InformatcPhysicScore")
                        .HasColumnType("integer");

                    b.Property<int>("MathAlgebraGeometryScore")
                        .HasColumnType("integer");

                    b.Property<int>("PCode")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RussianLanguageScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCompetitiveScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEntranceTestsScore")
                        .HasColumnType("integer");

                    b.HasKey("UniqueCode");

                    b.HasIndex("TotalCompetitiveScore");

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.ToTable("Applicants");
                });
#pragma warning restore 612, 618
        }
    }
}
